# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Ui_MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCharts import QChartView
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGridLayout,
    QGroupBox, QLabel, QLineEdit, QMainWindow,
    QPushButton, QRadioButton, QScrollBar, QSizePolicy,
    QStatusBar, QWidget)

from widget.Demo import Demo

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1325, 767)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = Demo(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(8, 8, 1073, 471))
        self.widget.setAutoFillBackground(False)
        self.graphicsView = QChartView(self.widget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(0, 0, 1073, 465))
        self.graphicsView.setStyleSheet(u"border: 1px solid red;")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(8, 496, 593, 241))
        font = QFont()
        font.setPointSize(7)
        self.groupBox.setFont(font)
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(8, 24, 153, 41))
        self.radioButton = QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(8, 16, 49, 23))
        self.radioButton.setChecked(True)
        self.radioButton_2 = QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(64, 16, 49, 23))
        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(8, 64, 113, 81))
        self.radioButton_3 = QRadioButton(self.groupBox_3)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(10, 20, 61, 23))
        self.radioButton_4 = QRadioButton(self.groupBox_3)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(10, 40, 61, 23))
        self.radioButton_4.setChecked(True)
        self.radioButton_5 = QRadioButton(self.groupBox_3)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(10, 60, 61, 23))
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(168, 24, 191, 41))
        self.checkBox = QCheckBox(self.groupBox_4)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(10, 16, 61, 23))
        self.checkBox.setChecked(True)
        self.checkBox_2 = QCheckBox(self.groupBox_4)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(70, 16, 61, 23))
        self.checkBox_3 = QCheckBox(self.groupBox_4)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(130, 16, 61, 23))
        self.groupBox_5 = QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(128, 64, 313, 81))
        self.checkBox_4 = QCheckBox(self.groupBox_5)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(10, 20, 92, 23))
        self.checkBox_5 = QCheckBox(self.groupBox_5)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(10, 40, 92, 23))
        self.checkBox_6 = QCheckBox(self.groupBox_5)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(10, 60, 92, 23))
        self.checkBox_7 = QCheckBox(self.groupBox_5)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(110, 60, 92, 23))
        self.checkBox_8 = QCheckBox(self.groupBox_5)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(110, 20, 92, 23))
        self.checkBox_8.setChecked(True)
        self.checkBox_9 = QCheckBox(self.groupBox_5)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setGeometry(QRect(110, 40, 92, 23))
        self.checkBox_10 = QCheckBox(self.groupBox_5)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(210, 60, 92, 23))
        self.checkBox_11 = QCheckBox(self.groupBox_5)
        self.checkBox_11.setObjectName(u"checkBox_11")
        self.checkBox_11.setGeometry(QRect(210, 40, 92, 23))
        self.checkBox_12 = QCheckBox(self.groupBox_5)
        self.checkBox_12.setObjectName(u"checkBox_12")
        self.checkBox_12.setGeometry(QRect(210, 20, 92, 23))
        self.checkBox_12.setChecked(True)
        self.btnParaments = QPushButton(self.groupBox)
        self.btnParaments.setObjectName(u"btnParaments")
        self.btnParaments.setGeometry(QRect(80, 180, 89, 25))
        self.btnRestoreDefaults = QPushButton(self.groupBox)
        self.btnRestoreDefaults.setObjectName(u"btnRestoreDefaults")
        self.btnRestoreDefaults.setGeometry(QRect(180, 180, 131, 25))
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(608, 496, 265, 241))
        self.groupBox_6.setFont(font)
        self.label_25 = QLabel(self.groupBox_6)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(8, 168, 105, 20))
        self.label_26 = QLabel(self.groupBox_6)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(8, 184, 105, 20))
        self.label_27 = QLabel(self.groupBox_6)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(112, 168, 41, 18))
        self.label_27.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_28 = QLabel(self.groupBox_6)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(112, 184, 41, 18))
        self.label_28.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.checkBox_13 = QCheckBox(self.groupBox_6)
        self.checkBox_13.setObjectName(u"checkBox_13")
        self.checkBox_13.setGeometry(QRect(168, 176, 57, 24))
        self.checkBox_13.setChecked(True)
        self.gridLayoutWidget = QWidget(self.groupBox_6)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(8, 24, 251, 143))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.comboBox_4 = QComboBox(self.gridLayoutWidget)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")

        self.gridLayout.addWidget(self.comboBox_4, 4, 1, 1, 1)

        self.comboBox_8 = QComboBox(self.gridLayoutWidget)
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.setObjectName(u"comboBox_8")

        self.gridLayout.addWidget(self.comboBox_8, 2, 2, 1, 1)

        self.comboBox_7 = QComboBox(self.gridLayoutWidget)
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.setObjectName(u"comboBox_7")

        self.gridLayout.addWidget(self.comboBox_7, 3, 2, 1, 1)

        self.lineEdit_4 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")

        self.gridLayout.addWidget(self.lineEdit_4, 4, 4, 1, 1)

        self.label = QLabel(self.gridLayoutWidget)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        self.comboBox = QComboBox(self.gridLayoutWidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")

        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)

        self.comboBox_10 = QComboBox(self.gridLayoutWidget)
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.setObjectName(u"comboBox_10")

        self.gridLayout.addWidget(self.comboBox_10, 1, 3, 1, 1)

        self.comboBox_2 = QComboBox(self.gridLayoutWidget)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")

        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)

        self.lineEdit_2 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")

        self.gridLayout.addWidget(self.lineEdit_2, 2, 4, 1, 1)

        self.comboBox_9 = QComboBox(self.gridLayoutWidget)
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.setObjectName(u"comboBox_9")

        self.gridLayout.addWidget(self.comboBox_9, 3, 3, 1, 1)

        self.label_3 = QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)

        self.label_4 = QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)

        self.comboBox_3 = QComboBox(self.gridLayoutWidget)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")

        self.gridLayout.addWidget(self.comboBox_3, 3, 1, 1, 1)

        self.label_2 = QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)

        self.comboBox_5 = QComboBox(self.gridLayoutWidget)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")

        self.gridLayout.addWidget(self.comboBox_5, 4, 2, 1, 1)

        self.lineEdit = QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName(u"lineEdit")

        self.gridLayout.addWidget(self.lineEdit, 1, 4, 1, 1)

        self.lineEdit_3 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")

        self.gridLayout.addWidget(self.lineEdit_3, 3, 4, 1, 1)

        self.comboBox_6 = QComboBox(self.gridLayoutWidget)
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.setObjectName(u"comboBox_6")

        self.gridLayout.addWidget(self.comboBox_6, 1, 2, 1, 1)

        self.label_21 = QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName(u"label_21")

        self.gridLayout.addWidget(self.label_21, 0, 1, 1, 1)

        self.label_22 = QLabel(self.gridLayoutWidget)
        self.label_22.setObjectName(u"label_22")

        self.gridLayout.addWidget(self.label_22, 0, 2, 1, 1)

        self.label_23 = QLabel(self.gridLayoutWidget)
        self.label_23.setObjectName(u"label_23")

        self.gridLayout.addWidget(self.label_23, 0, 3, 1, 1)

        self.label_24 = QLabel(self.gridLayoutWidget)
        self.label_24.setObjectName(u"label_24")

        self.gridLayout.addWidget(self.label_24, 0, 4, 1, 1)

        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(880, 496, 201, 241))
        self.groupBox_7.setFont(font)
        self.groupBox_8 = QGroupBox(self.groupBox_7)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(8, 24, 120, 51))
        self.btnOpen = QPushButton(self.groupBox_8)
        self.btnOpen.setObjectName(u"btnOpen")
        self.btnOpen.setGeometry(QRect(0, 20, 51, 25))
        self.btnSave = QPushButton(self.groupBox_8)
        self.btnSave.setObjectName(u"btnSave")
        self.btnSave.setGeometry(QRect(60, 20, 51, 25))
        self.btnExport = QPushButton(self.groupBox_7)
        self.btnExport.setObjectName(u"btnExport")
        self.btnExport.setGeometry(QRect(140, 40, 51, 25))
        self.groupBox_9 = QGroupBox(self.groupBox_7)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(8, 72, 181, 121))
        self.btnCopyGraph = QPushButton(self.groupBox_9)
        self.btnCopyGraph.setObjectName(u"btnCopyGraph")
        self.btnCopyGraph.setGeometry(QRect(10, 30, 161, 25))
        self.btnCoovStats = QPushButton(self.groupBox_9)
        self.btnCoovStats.setObjectName(u"btnCoovStats")
        self.btnCoovStats.setGeometry(QRect(10, 60, 161, 25))
        self.btnCopyScreen = QPushButton(self.groupBox_9)
        self.btnCopyScreen.setObjectName(u"btnCopyScreen")
        self.btnCopyScreen.setGeometry(QRect(10, 90, 161, 25))
        self.label_29 = QLabel(self.groupBox_7)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 200, 58, 18))
        self.label_30 = QLabel(self.groupBox_7)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 220, 58, 18))
        self.label_31 = QLabel(self.groupBox_7)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(70, 200, 31, 18))
        self.label_32 = QLabel(self.groupBox_7)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(70, 220, 31, 18))
        self.label_33 = QLabel(self.groupBox_7)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(160, 220, 31, 18))
        self.label_34 = QLabel(self.groupBox_7)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(100, 220, 58, 18))
        self.label_35 = QLabel(self.groupBox_7)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(100, 200, 58, 18))
        self.label_36 = QLabel(self.groupBox_7)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(160, 200, 31, 18))
        self.groupBox_10 = QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(1088, 0, 231, 737))
        self.groupBox_10.setFont(font)
        self.groupBox_11 = QGroupBox(self.groupBox_10)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(8, 690, 217, 41))
        self.btnReset = QPushButton(self.groupBox_11)
        self.btnReset.setObjectName(u"btnReset")
        self.btnReset.setGeometry(QRect(8, 8, 201, 25))
        self.groupBox_12 = QGroupBox(self.groupBox_10)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(10, 582, 217, 105))
        self.btnRun = QPushButton(self.groupBox_12)
        self.btnRun.setObjectName(u"btnRun")
        self.btnRun.setGeometry(QRect(8, 10, 201, 41))
        self.btnStop = QPushButton(self.groupBox_12)
        self.btnStop.setObjectName(u"btnStop")
        self.btnStop.setGeometry(QRect(8, 60, 201, 41))
        self.groupBox_13 = QGroupBox(self.groupBox_10)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(10, 470, 211, 101))
        self.btnSetCaptureTriggers = QPushButton(self.groupBox_13)
        self.btnSetCaptureTriggers.setObjectName(u"btnSetCaptureTriggers")
        self.btnSetCaptureTriggers.setGeometry(QRect(10, 70, 191, 25))
        self.label_5 = QLabel(self.groupBox_13)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 30, 67, 17))
        self.label_6 = QLabel(self.groupBox_13)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 50, 67, 17))
        self.groupBox_14 = QGroupBox(self.groupBox_10)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(10, 330, 211, 131))
        self.comboBox_11 = QComboBox(self.groupBox_14)
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.setObjectName(u"comboBox_11")
        self.comboBox_11.setGeometry(QRect(10, 50, 86, 25))
        self.comboBox_13 = QComboBox(self.groupBox_14)
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.setObjectName(u"comboBox_13")
        self.comboBox_13.setGeometry(QRect(10, 100, 86, 25))
        self.label_37 = QLabel(self.groupBox_14)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(40, 80, 58, 18))
        self.label_38 = QLabel(self.groupBox_14)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(100, 30, 41, 18))
        self.label_41 = QLabel(self.groupBox_14)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(140, 30, 41, 18))
        self.label_42 = QLabel(self.groupBox_14)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(110, 50, 41, 18))
        self.label_43 = QLabel(self.groupBox_14)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(110, 80, 41, 18))
        self.label_44 = QLabel(self.groupBox_14)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(110, 100, 41, 18))
        self.label_45 = QLabel(self.groupBox_14)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(150, 50, 41, 18))
        self.label_46 = QLabel(self.groupBox_14)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(150, 100, 41, 18))
        self.label_47 = QLabel(self.groupBox_14)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(150, 80, 41, 18))
        self.label_48 = QLabel(self.groupBox_14)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(180, 50, 41, 18))
        self.label_49 = QLabel(self.groupBox_14)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(180, 100, 41, 18))
        self.groupBox_15 = QGroupBox(self.groupBox_10)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(10, 100, 211, 231))
        self.label_7 = QLabel(self.groupBox_15)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 67, 17))
        self.label_8 = QLabel(self.groupBox_15)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 50, 67, 17))
        self.label_9 = QLabel(self.groupBox_15)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 70, 67, 17))
        self.label_10 = QLabel(self.groupBox_15)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 90, 67, 17))
        self.label_11 = QLabel(self.groupBox_15)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 110, 67, 17))
        self.label_12 = QLabel(self.groupBox_15)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 130, 67, 17))
        self.label_13 = QLabel(self.groupBox_15)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 150, 67, 17))
        self.radioButton_6 = QRadioButton(self.groupBox_15)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.radioButton_6.setGeometry(QRect(10, 200, 61, 24))
        self.radioButton_6.setChecked(True)
        self.radioButton_7 = QRadioButton(self.groupBox_15)
        self.radioButton_7.setObjectName(u"radioButton_7")
        self.radioButton_7.setGeometry(QRect(80, 200, 61, 24))
        self.radioButton_8 = QRadioButton(self.groupBox_15)
        self.radioButton_8.setObjectName(u"radioButton_8")
        self.radioButton_8.setGeometry(QRect(140, 200, 61, 24))
        self.btnmAmWSwitch = QPushButton(self.groupBox_10)
        self.btnmAmWSwitch.setObjectName(u"btnmAmWSwitch")
        self.btnmAmWSwitch.setGeometry(QRect(150, 70, 71, 25))
        self.btnVoutSwitch = QPushButton(self.groupBox_10)
        self.btnVoutSwitch.setObjectName(u"btnVoutSwitch")
        self.btnVoutSwitch.setGeometry(QRect(120, 10, 101, 25))
        self.btnSetVout = QPushButton(self.groupBox_10)
        self.btnSetVout.setObjectName(u"btnSetVout")
        self.btnSetVout.setGeometry(QRect(120, 40, 101, 25))
        self.label_14 = QLabel(self.groupBox_10)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 10, 58, 18))
        self.label_15 = QLabel(self.groupBox_10)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 10, 58, 18))
        self.label_16 = QLabel(self.groupBox_10)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 40, 58, 18))
        self.label_17 = QLabel(self.groupBox_10)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(50, 40, 58, 18))
        self.label_18 = QLabel(self.groupBox_10)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 60, 101, 18))
        self.label_19 = QLabel(self.groupBox_10)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 80, 58, 18))
        self.label_20 = QLabel(self.groupBox_10)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(50, 80, 58, 18))
        self.horizontalScrollBar = QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setObjectName(u"horizontalScrollBar")
        self.horizontalScrollBar.setGeometry(QRect(10, 480, 1071, 16))
        self.horizontalScrollBar.setOrientation(Qt.Horizontal)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"LEGEND", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"VOLTAGE SOURCE", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"Main", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"Aux", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"USB PASSTHROUGH", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.radioButton_5.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"DISPLAY CHANNELS", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Main", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"USB", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"Aux", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"DISPLAY MEASUREMENTS", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"Power Avg", None))
        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"Power Min", None))
        self.checkBox_6.setText(QCoreApplication.translate("MainWindow", u"Power Max", None))
        self.checkBox_7.setText(QCoreApplication.translate("MainWindow", u"Current", None))
        self.checkBox_8.setText(QCoreApplication.translate("MainWindow", u"Current Avg", None))
        self.checkBox_9.setText(QCoreApplication.translate("MainWindow", u"Current Min", None))
        self.checkBox_10.setText(QCoreApplication.translate("MainWindow", u"Voltage", None))
        self.checkBox_11.setText(QCoreApplication.translate("MainWindow", u"Voltage Min", None))
        self.checkBox_12.setText(QCoreApplication.translate("MainWindow", u"Voltage Avg", None))
        self.btnParaments.setText(QCoreApplication.translate("MainWindow", u"Paraments", None))
        self.btnRestoreDefaults.setText(QCoreApplication.translate("MainWindow", u"Restore Defaults", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"GRAPH SCALE", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Dropped samples", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Dropped connections", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.checkBox_13.setText(QCoreApplication.translate("MainWindow", u"Subgrid", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("MainWindow", u"V", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", u"mV", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("MainWindow", u"uV", None))

        self.comboBox_8.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_8.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_8.setItemText(2, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_8.setItemText(3, QCoreApplication.translate("MainWindow", u"10", None))
        self.comboBox_8.setItemText(4, QCoreApplication.translate("MainWindow", u"20", None))
        self.comboBox_8.setItemText(5, QCoreApplication.translate("MainWindow", u"50", None))
        self.comboBox_8.setItemText(6, QCoreApplication.translate("MainWindow", u"100", None))
        self.comboBox_8.setItemText(7, QCoreApplication.translate("MainWindow", u"200", None))
        self.comboBox_8.setItemText(8, QCoreApplication.translate("MainWindow", u"500", None))

        self.comboBox_7.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_7.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_7.setItemText(2, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_7.setItemText(3, QCoreApplication.translate("MainWindow", u"10", None))
        self.comboBox_7.setItemText(4, QCoreApplication.translate("MainWindow", u"20", None))
        self.comboBox_7.setItemText(5, QCoreApplication.translate("MainWindow", u"50", None))
        self.comboBox_7.setItemText(6, QCoreApplication.translate("MainWindow", u"100", None))
        self.comboBox_7.setItemText(7, QCoreApplication.translate("MainWindow", u"200", None))
        self.comboBox_7.setItemText(8, QCoreApplication.translate("MainWindow", u"500", None))

        self.lineEdit_4.setText(QCoreApplication.translate("MainWindow", u"0.00", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"s", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"ms", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"us", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"min", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"hr", None))

        self.comboBox_10.setItemText(0, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_10.setItemText(1, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_10.setItemText(2, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_10.setItemText(3, QCoreApplication.translate("MainWindow", u"10", None))

        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"W", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"mW", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"uW", None))

        self.lineEdit_2.setText(QCoreApplication.translate("MainWindow", u"0.00", None))
        self.comboBox_9.setItemText(0, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_9.setItemText(1, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_9.setItemText(2, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_9.setItemText(3, QCoreApplication.translate("MainWindow", u"10", None))
        self.comboBox_9.setItemText(4, QCoreApplication.translate("MainWindow", u"20", None))

        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Current", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Voltage", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", u"A", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("MainWindow", u"mA", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("MainWindow", u"uA", None))

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Power", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_5.setItemText(3, QCoreApplication.translate("MainWindow", u"10", None))
        self.comboBox_5.setItemText(4, QCoreApplication.translate("MainWindow", u"20", None))
        self.comboBox_5.setItemText(5, QCoreApplication.translate("MainWindow", u"50", None))
        self.comboBox_5.setItemText(6, QCoreApplication.translate("MainWindow", u"100", None))
        self.comboBox_5.setItemText(7, QCoreApplication.translate("MainWindow", u"200", None))
        self.comboBox_5.setItemText(8, QCoreApplication.translate("MainWindow", u"500", None))

        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"0.00", None))
        self.lineEdit_3.setText(QCoreApplication.translate("MainWindow", u"0.00", None))
        self.comboBox_6.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_6.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_6.setItemText(2, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_6.setItemText(3, QCoreApplication.translate("MainWindow", u"10", None))
        self.comboBox_6.setItemText(4, QCoreApplication.translate("MainWindow", u"20", None))
        self.comboBox_6.setItemText(5, QCoreApplication.translate("MainWindow", u"40", None))
        self.comboBox_6.setItemText(6, QCoreApplication.translate("MainWindow", u"50", None))
        self.comboBox_6.setItemText(7, QCoreApplication.translate("MainWindow", u"100", None))

        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Unit", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Units/tick", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"#Ticks", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Offset", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"DATA", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"CAPTURE FILE", None))
        self.btnOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.btnSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.btnExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"GRAPHICS", None))
        self.btnCopyGraph.setText(QCoreApplication.translate("MainWindow", u"Copy Graph", None))
        self.btnCoovStats.setText(QCoreApplication.translate("MainWindow", u"Coov Stats", None))
        self.btnCopyScreen.setText(QCoreApplication.translate("MainWindow", u"Copy Screen", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"HW rev", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"FW rev", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"?", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"5.0.0.25", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"SW rev", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Post rev", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"?", None))
        self.groupBox_10.setTitle("")
        self.groupBox_11.setTitle("")
        self.btnReset.setText(QCoreApplication.translate("MainWindow", u"RESET", None))
        self.groupBox_12.setTitle("")
        self.btnRun.setText(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.btnStop.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"CAPTURE TRIGGERS", None))
        self.btnSetCaptureTriggers.setText(QCoreApplication.translate("MainWindow", u"Set Capture Triggers", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("MainWindow", u"CURSORS", None))
        self.comboBox_11.setItemText(0, QCoreApplication.translate("MainWindow", u"None", None))
        self.comboBox_11.setItemText(1, QCoreApplication.translate("MainWindow", u"Avg Main Current", None))
        self.comboBox_11.setItemText(2, QCoreApplication.translate("MainWindow", u"Avg Main Voltage", None))

        self.comboBox_13.setItemText(0, QCoreApplication.translate("MainWindow", u"None", None))
        self.comboBox_13.setItemText(1, QCoreApplication.translate("MainWindow", u"Avg Main Current", None))
        self.comboBox_13.setItemText(2, QCoreApplication.translate("MainWindow", u"Avg Main Voltage", None))

        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Delta", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Value", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"-.--", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"-.--", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"-.--", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"-.--", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"-.--", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"-.--", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"ms", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"ms", None))
        self.groupBox_15.setTitle(QCoreApplication.translate("MainWindow", u"CAPTURE STATS", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Sample", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.radioButton_6.setText(QCoreApplication.translate("MainWindow", u"Main", None))
        self.radioButton_7.setText(QCoreApplication.translate("MainWindow", u"USB", None))
        self.radioButton_8.setText(QCoreApplication.translate("MainWindow", u"Aux", None))
        self.btnmAmWSwitch.setText(QCoreApplication.translate("MainWindow", u"mW", None))
        self.btnVoutSwitch.setText(QCoreApplication.translate("MainWindow", u"Vout Disable", None))
        self.btnSetVout.setText(QCoreApplication.translate("MainWindow", u"Set Vout", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Vout", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"ENABLED", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"2.00", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Inst Current", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"-.--", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"mA", None))
    # retranslateUi

