# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Ui_TriggerSettingsWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QHBoxLayout,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QRadioButton, QSizePolicy, QWidget)

class Ui_TriggerSettingsWindow(object):
    def setupUi(self, TriggerSettingsWindow):
        if not TriggerSettingsWindow.objectName():
            TriggerSettingsWindow.setObjectName(u"TriggerSettingsWindow")
        TriggerSettingsWindow.resize(800, 600)
        self.centralwidget = QWidget(TriggerSettingsWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(8, 8, 785, 297))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.widget = QWidget(self.horizontalLayoutWidget)
        self.widget.setObjectName(u"widget")
        font = QFont()
        font.setPointSize(10)
        self.widget.setFont(font)
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(8, 0, 67, 17))
        self.radioButton = QRadioButton(self.widget)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(8, 24, 89, 23))
        self.radioButton_3 = QRadioButton(self.widget)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(8, 56, 89, 23))
        self.radioButton_4 = QRadioButton(self.widget)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(8, 88, 89, 23))
        self.radioButton_5 = QRadioButton(self.widget)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(8, 120, 89, 23))
        self.radioButton_6 = QRadioButton(self.widget)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.radioButton_6.setGeometry(QRect(8, 152, 89, 23))
        self.checkBox = QCheckBox(self.widget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(8, 208, 121, 23))
        self.checkBox_3 = QCheckBox(self.widget)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(8, 240, 121, 23))
        self.lineEdit = QLineEdit(self.widget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(136, 240, 65, 25))
        self.lineEdit_2 = QLineEdit(self.widget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(136, 208, 65, 25))
        self.label_5 = QLabel(self.widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(208, 240, 145, 17))
        self.label_6 = QLabel(self.widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(208, 208, 145, 17))
        self.lineEdit_3 = QLineEdit(self.widget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(104, 56, 65, 25))
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(176, 56, 57, 17))
        self.lineEdit_7 = QLineEdit(self.widget)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(104, 88, 65, 25))
        self.comboBox = QComboBox(self.widget)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(176, 88, 86, 25))
        self.comboBox_2 = QComboBox(self.widget)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(104, 120, 86, 25))
        self.comboBox_3 = QComboBox(self.widget)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(192, 120, 86, 25))
        self.lineEdit_12 = QLineEdit(self.widget)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(280, 120, 65, 25))
        self.label_14 = QLabel(self.widget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(352, 120, 25, 17))

        self.horizontalLayout.addWidget(self.widget)

        self.widget_2 = QWidget(self.horizontalLayoutWidget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setFont(font)
        self.label_20 = QLabel(self.widget_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(176, 56, 57, 17))
        self.checkBox_10 = QCheckBox(self.widget_2)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(8, 240, 129, 23))
        self.radioButton_27 = QRadioButton(self.widget_2)
        self.radioButton_27.setObjectName(u"radioButton_27")
        self.radioButton_27.setGeometry(QRect(8, 88, 89, 23))
        self.lineEdit_19 = QLineEdit(self.widget_2)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(104, 88, 65, 25))
        self.label_22 = QLabel(self.widget_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(208, 208, 145, 17))
        self.lineEdit_20 = QLineEdit(self.widget_2)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(104, 120, 65, 25))
        self.checkBox_11 = QCheckBox(self.widget_2)
        self.checkBox_11.setObjectName(u"checkBox_11")
        self.checkBox_11.setGeometry(QRect(8, 208, 121, 23))
        self.radioButton_28 = QRadioButton(self.widget_2)
        self.radioButton_28.setObjectName(u"radioButton_28")
        self.radioButton_28.setGeometry(QRect(8, 24, 89, 23))
        self.label_24 = QLabel(self.widget_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(8, 0, 67, 17))
        self.radioButton_29 = QRadioButton(self.widget_2)
        self.radioButton_29.setObjectName(u"radioButton_29")
        self.radioButton_29.setGeometry(QRect(8, 56, 89, 23))
        self.lineEdit_21 = QLineEdit(self.widget_2)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.lineEdit_21.setGeometry(QRect(104, 56, 65, 25))
        self.radioButton_30 = QRadioButton(self.widget_2)
        self.radioButton_30.setObjectName(u"radioButton_30")
        self.radioButton_30.setGeometry(QRect(8, 120, 89, 23))
        self.lineEdit_22 = QLineEdit(self.widget_2)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.lineEdit_22.setGeometry(QRect(136, 208, 65, 25))
        self.label_25 = QLabel(self.widget_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(176, 88, 57, 17))
        self.label_26 = QLabel(self.widget_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(352, 152, 25, 17))
        self.radioButton_31 = QRadioButton(self.widget_2)
        self.radioButton_31.setObjectName(u"radioButton_31")
        self.radioButton_31.setGeometry(QRect(8, 152, 89, 23))
        self.comboBox_12 = QComboBox(self.widget_2)
        self.comboBox_12.setObjectName(u"comboBox_12")
        self.comboBox_12.setGeometry(QRect(104, 152, 86, 25))
        self.comboBox_13 = QComboBox(self.widget_2)
        self.comboBox_13.setObjectName(u"comboBox_13")
        self.comboBox_13.setGeometry(QRect(192, 152, 86, 25))
        self.lineEdit_23 = QLineEdit(self.widget_2)
        self.lineEdit_23.setObjectName(u"lineEdit_23")
        self.lineEdit_23.setGeometry(QRect(280, 152, 65, 25))
        self.label_21 = QLabel(self.widget_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(32, 272, 113, 17))
        self.comboBox_14 = QComboBox(self.widget_2)
        self.comboBox_14.setObjectName(u"comboBox_14")
        self.comboBox_14.setGeometry(QRect(200, 264, 86, 25))
        self.comboBox_15 = QComboBox(self.widget_2)
        self.comboBox_15.setObjectName(u"comboBox_15")
        self.comboBox_15.setGeometry(QRect(176, 120, 86, 25))

        self.horizontalLayout.addWidget(self.widget_2)

        self.btnOk = QPushButton(self.centralwidget)
        self.btnOk.setObjectName(u"btnOk")
        self.btnOk.setGeometry(QRect(288, 312, 89, 25))
        self.btnCancel = QPushButton(self.centralwidget)
        self.btnCancel.setObjectName(u"btnCancel")
        self.btnCancel.setGeometry(QRect(424, 312, 89, 25))
        TriggerSettingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TriggerSettingsWindow)

        QMetaObject.connectSlotsByName(TriggerSettingsWindow)
    # setupUi

    def retranslateUi(self, TriggerSettingsWindow):
        TriggerSettingsWindow.setWindowTitle(QCoreApplication.translate("TriggerSettingsWindow", u"Trigger Settings", None))
        self.label.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Start", None))
        self.radioButton.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Manual", None))
        self.radioButton_3.setText(QCoreApplication.translate("TriggerSettingsWindow", u"After", None))
        self.radioButton_4.setText(QCoreApplication.translate("TriggerSettingsWindow", u"After", None))
        self.radioButton_5.setText(QCoreApplication.translate("TriggerSettingsWindow", u"After", None))
        self.radioButton_6.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Immediate", None))
        self.checkBox.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Capture", None))
        self.checkBox_3.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Delay Capture", None))
        self.label_5.setText(QCoreApplication.translate("TriggerSettingsWindow", u"samples after trigger", None))
        self.label_6.setText(QCoreApplication.translate("TriggerSettingsWindow", u"samples after trigger", None))
        self.label_9.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Markers", None))
        self.label_14.setText(QCoreApplication.translate("TriggerSettingsWindow", u"mW", None))
        self.label_20.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Markers", None))
        self.checkBox_10.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Export to CSV file", None))
        self.radioButton_27.setText(QCoreApplication.translate("TriggerSettingsWindow", u"After", None))
        self.label_22.setText(QCoreApplication.translate("TriggerSettingsWindow", u"samples after trigger", None))
        self.checkBox_11.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Capture", None))
        self.radioButton_28.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Manual", None))
        self.label_24.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Stop", None))
        self.radioButton_29.setText(QCoreApplication.translate("TriggerSettingsWindow", u"After", None))
        self.radioButton_30.setText(QCoreApplication.translate("TriggerSettingsWindow", u"After", None))
        self.label_25.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Samples", None))
        self.label_26.setText(QCoreApplication.translate("TriggerSettingsWindow", u"mW", None))
        self.radioButton_31.setText(QCoreApplication.translate("TriggerSettingsWindow", u"After", None))
        self.label_21.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Export Granularity", None))
        self.btnOk.setText(QCoreApplication.translate("TriggerSettingsWindow", u"OK", None))
        self.btnCancel.setText(QCoreApplication.translate("TriggerSettingsWindow", u"Cancel", None))
    # retranslateUi

